language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - FLASK=0.10
  - FLASK=0.10.1
  - FLASK=0.10 speaklater
  - FLASK=0.10.1 speaklater
  - FLASK=0.11
  - FLASK=0.11.1
  - FLASK=0.12
  - FLASK=0.12.1
  - FLASK=0.12.2
install:
  - pip install Flask==$FLASK
  - pip install pycodestyle==2.5.0 pytest==3.0.3 pytest-cov==2.3.1
before_script:
 - pycodestyle flask_json.py
script: py.test
